#!/bin/bash

# Script to read user input and print a greeting message

# Ask user for their name
#-----------------------------------------------------
<<com
echo  "trick NO:1" 

echo "what is you name:"
read name
echo "my name is: $name "
com
#-------------------

echo "TRICK NO 2---"
read -p  "Plz Enter Your Name:" name
echo "My Name Is: $name"

